### ISSUE TITLE
[JENKINS-72696] Jenkins can not start on a TCK compliant JVM that does not have MD5 support

### ISSUE THREAD

**Issue by lemeurherve** [lemeurherve-org/demo-2025-11-22#22]
<p><a href="https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/MessageDigest.html" class="external-link" target="_blank" rel="nofollow noopener">Java17</a>(actually <a href="https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/security/MessageDigest.html" class="external-link" target="_blank" rel="nofollow noopener">JDK14</a> but 17 is the LTS) removed the mandatory requirement that <tt>MD5</tt> needed to be a supported <tt>MessageDigest</tt>.</p>

<p>If you attempt to start Jenkins on a JVM that does not have MD5 available it ends in a big mess.</p>

<pre>
2024-02-09 15:02:43.444+0000 [id=25]    SEVERE  hudson.util.BootFailure#publish: Failed to initialize Jenkins
java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
at hudson.Util.getMd5(Util.java:664)
at hudson.Util.getDigestOf(Util.java:640)
Caused: java.io.IOException: MD5 not installed
at hudson.Util.getDigestOf(Util.java:648)
at hudson.Util.getDigestOf(Util.java:670)
Caused: java.lang.Error
at hudson.Util.getDigestOf(Util.java:672)
at jenkins.model.Jenkins.computeVersion(Jenkins.java:5556)
at jenkins.model.Jenkins.<init>(Jenkins.java:926)
at hudson.model.Hudson.<init>(Hudson.java:86)
at hudson.model.Hudson.<init>(Hudson.java:82)
at hudson.WebAppMain$3.run(WebAppMain.java:248)
Caused: hudson.util.HudsonFailedToLoad
at hudson.WebAppMain$3.run(WebAppMain.java:262)
Exception in thread <span class="code-quote">"Jenkins initialization thread"</span> java.lang.Error: java.io.IOException: MD5 not installed
at hudson.Util.getDigestOf(Util.java:672)
at jenkins.model.Jenkins.computeVersion(Jenkins.java:5556)
at jenkins.model.Jenkins.<init>(Jenkins.java:926)
at hudson.model.Hudson.<init>(Hudson.java:86)
at hudson.model.Hudson.<init>(Hudson.java:82)
at hudson.WebAppMain$3.run(WebAppMain.java:248)
Caused by: java.io.IOException: MD5 not installed
at hudson.Util.getDigestOf(Util.java:648)
at hudson.Util.getDigestOf(Util.java:670)
... 5 more
Caused by: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
at hudson.Util.getMd5(Util.java:664)
at hudson.Util.getDigestOf(Util.java:640)
... 6 more
</pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/teilo.png" title="teilo's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=teilo">teilo</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-72696" target="_blank">Jenkins can not start on a TCK compliant JVM that does not have MD5 support</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: java17-compatibility, jdk, jdk-17
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-22
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p><a href="https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/MessageDigest.html" class="external-link" target="_blank" rel="nofollow noopener">Java17</a>(actually <a href="https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/security/MessageDigest.html" class="external-link" target="_blank" rel="nofollow noopener">JDK14</a> but 17 is the LTS) removed the mandatory requirement that <tt>MD5</tt> needed to be a supported <tt>MessageDigest</tt>.</p>

<p>If you attempt to start Jenkins on a JVM that does not have MD5 available it ends in a big mess.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2024-02-09 15:02:43.444+0000 [id=25]    SEVERE  hudson.util.BootFailure#publish: Failed to initialize Jenkins
java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
        at hudson.Util.getMd5(Util.java:664)
        at hudson.Util.getDigestOf(Util.java:640)
Caused: java.io.IOException: MD5 not installed
        at hudson.Util.getDigestOf(Util.java:648)
        at hudson.Util.getDigestOf(Util.java:670)
Caused: java.lang.Error
        at hudson.Util.getDigestOf(Util.java:672)
        at jenkins.model.Jenkins.computeVersion(Jenkins.java:5556)
        at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:926)
        at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)
        at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)
        at hudson.WebAppMain$3.run(WebAppMain.java:248)
Caused: hudson.util.HudsonFailedToLoad
        at hudson.WebAppMain$3.run(WebAppMain.java:262)
Exception in thread <span class="code-quote">"Jenkins initialization thread"</span> java.lang.Error: java.io.IOException: MD5 not installed
        at hudson.Util.getDigestOf(Util.java:672)
        at jenkins.model.Jenkins.computeVersion(Jenkins.java:5556)
        at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:926)
        at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)
        at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)
        at hudson.WebAppMain$3.run(WebAppMain.java:248)
Caused by: java.io.IOException: MD5 not installed
        at hudson.Util.getDigestOf(Util.java:648)
        at hudson.Util.getDigestOf(Util.java:670)
        ... 5 more
Caused by: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
        at hudson.Util.getMd5(Util.java:664)
        at hudson.Util.getDigestOf(Util.java:640)
        ... 6 more
</pre>
</div></div></pre>
</details>
</details>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/teilo.png" title="teilo's avatar" /> teilo:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-72696?focusedId=445078&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-445078">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>obviously this is just the outer layer of the onion, once you get past this, there is various other code using MD5 (either directly or indirectly via <tt>Util.getDigestOf()</tt>  </p>
</pre>
</details>

</ul>
</details>

<p>obviously this is just the outer layer of the onion, once you get past this, there is various other code using MD5 (either directly or indirectly via <tt>Util.getDigestOf()</tt>  </p>
