### ISSUE TITLE
[JENKINS-73006] Error HTTP 503 when trying to update Jenkins or any plugin

### ISSUE THREAD

**Issue by lemeurherve** [lemeurherve-org/demo-2025-11-22#79]
<p>I'm getting an error (HTTP 503) when I try to update Jenkins or any plugin using Update Center.</p>

<p>When I try to download the same file using the browser or command line, the download occurs normally.</p>

<p>I couln't find any workaround to this problem.</p>

<p>Here is the exception:</p>

<p> </p>

<pre>
java.io.IOException: Server returned HTTP response code: 503 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3118)
    at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
    at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
    at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:394)
    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1302)
Caused: java.io.IOException: Server returned HTTP response code: 503 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1321)
Caused: java.io.IOException: Failed to load https:<span class="code-comment">//updates.jenkins.io/download/war/2.440.2/jenkins.war to /usr/share/jenkins/jenkins.war.tmp
</span>    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1332)
Caused: java.io.IOException: Failed to download from https:<span class="code-comment">//updates.jenkins.io/download/war/2.440.2/jenkins.war (redirected to: https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war)
</span>    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1366)
    at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1923)
    at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1897)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829) </pre>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rafaelsennadasilva.jpg" title="rafaelsennadasilva's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rafaelsennadasilva">rafaelsennadasilva</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006" target="_blank">Error HTTP 503 when trying to update Jenkins or any plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-22
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I'm getting an error (HTTP 503) when I try to update Jenkins or any plugin using Update Center.</p>

<p>When I try to download the same file using the browser or command line, the download occurs normally.</p>

<p>I couln't find any workaround to this problem.</p>

<p>Here is the exception:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.io.IOException: Server returned HTTP response code: 503 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3118)
    at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
    at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
    at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:394)
    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1302)
Caused: java.io.IOException: Server returned HTTP response code: 503 <span class="code-keyword">for</span> URL: https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1321)
Caused: java.io.IOException: Failed to load https:<span class="code-comment">//updates.jenkins.io/download/war/2.440.2/jenkins.war to /usr/share/jenkins/jenkins.war.tmp
</span>    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1332)
Caused: java.io.IOException: Failed to download from https:<span class="code-comment">//updates.jenkins.io/download/war/2.440.2/jenkins.war (redirected to: https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war)
</span>    at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1366)
    at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1923)
    at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1897)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829) </pre>
</div></div>
<p> </p>

<p> </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.414.2 running on docker (20.10.18)<br/>
There is no proxy configured
```
</details>
<details><summary><i>2 attachments</i></summary>

- [image-2024-04-12-15-32-36-481.png](https://issues.jenkins.io/secure/attachment/62448/image-2024-04-12-15-32-36-481.png)
  > ![image-2024-04-12-15-32-36-481.png](https://issues.jenkins.io/secure/attachment/62448/image-2024-04-12-15-32-36-481.png)
- [image.png](https://issues.jenkins.io/secure/attachment/62447/image.png)
  > ![image.png](https://issues.jenkins.io/secure/attachment/62447/image.png)
</details>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446726&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446726">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Thanks for reporting an issue.  I'm not able to duplicate the issue.</p>

<p>When I open <a href="https://get.jenkins.io/war-stable/2.440.2/jenkins.war?mirrorlist" class="external-link" target="_blank" rel="nofollow noopener">https://get.jenkins.io/war-stable/2.440.2/jenkins.war?mirrorlist</a> , I see the list of all Jenkins mirrors of that release.  All 9 mirrors are healthy.</p>

<p>In the last 24 hours of monitoring, I don't see any indications of a failure from that host.  I only check its response every few minutes, but none of those samples have detected an HTTP 503.</p>

<p>The graph for the last 24 hours looks like this:</p>

<p> <span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62447/62447_image.png" style="border: 0px solid black" /></span> </p>

<p>Are you still seeing the failure?</p>
</pre>
</details>

</ul>
</details>

<p>Thanks for reporting an issue.  I'm not able to duplicate the issue.</p>

<p>When I open <a href="https://get.jenkins.io/war-stable/2.440.2/jenkins.war?mirrorlist" class="external-link" target="_blank" rel="nofollow noopener">https://get.jenkins.io/war-stable/2.440.2/jenkins.war?mirrorlist</a> , I see the list of all Jenkins mirrors of that release.  All 9 mirrors are healthy.</p>

<p>In the last 24 hours of monitoring, I don't see any indications of a failure from that host.  I only check its response every few minutes, but none of those samples have detected an HTTP 503.</p>

<p>The graph for the last 24 hours looks like this:</p>

<p> <span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62447/62447_image.png" style="border: 0px solid black" /></span> </p>

<p>Are you still seeing the failure?</p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rafaelsennadasilva.jpg" title="rafaelsennadasilva's avatar" /> rafaelsennadasilva:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446728&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446728">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yes, still happening here.</p>

<p>Do you know some other reason for this error to occur?</p>

<p>Or where I can collect logs with more information</p>
</pre>
</details>

</ul>
</details>

<p>Yes, still happening here.</p>

<p>Do you know some other reason for this error to occur?</p>

<p>Or where I can collect logs with more information</p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rafaelsennadasilva.jpg" title="rafaelsennadasilva's avatar" /> rafaelsennadasilva:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446729&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446729">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62448/62448_image-2024-04-12-15-32-36-481.png" height="682" width="1423" style="border: 0px solid black" /></span></p>
</pre>
</details>

</ul>
</details>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62448/62448_image-2024-04-12-15-32-36-481.png" height="682" width="1423" style="border: 0px solid black" /></span></p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446731&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446731">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Do you have a proxy between your Jenkins controller and <a href="https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</a> ?  Check the "Manage Jenkins" =&gt; "System" configuration to confirm that no proxy is configured.</p>

<p>Can you reach any of the other Jenkins mirrors like:</p>

<ul>
	<li><a href="https://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirror.xmission.com/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirror.xmission.com/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.belnet.be/mirror/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.belnet.be/mirror/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.halifax.rwth-aachen.de/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.halifax.rwth-aachen.de/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://sg.mirror.servanamanaged.com/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://sg.mirror.servanamanaged.com/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirror.freedif.org/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirror.freedif.org/jenkins/war-stable/2.440.2/jenkins.war</a></li>
</ul>


</pre>
</details>

</ul>
</details>

<p>Do you have a proxy between your Jenkins controller and <a href="https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</a> ?  Check the "Manage Jenkins" => "System" configuration to confirm that no proxy is configured.</p>

<p>Can you reach any of the other Jenkins mirrors like:</p>

<ul>
	<li><a href="https://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirror.xmission.com/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirror.xmission.com/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.belnet.be/mirror/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.belnet.be/mirror/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.halifax.rwth-aachen.de/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.halifax.rwth-aachen.de/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://sg.mirror.servanamanaged.com/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://sg.mirror.servanamanaged.com/jenkins/war-stable/2.440.2/jenkins.war</a></li>
	<li><a href="https://mirror.freedif.org/jenkins/war-stable/2.440.2/jenkins.war" class="external-link" target="_blank" rel="nofollow noopener">https://mirror.freedif.org/jenkins/war-stable/2.440.2/jenkins.war</a></li>
</ul>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rafaelsennadasilva.jpg" title="rafaelsennadasilva's avatar" /> rafaelsennadasilva:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446732&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446732">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>There shouldn't be any proxy configured. I didn't find any proxy setting in "Manage Jenkins" =&gt; "System".</p>

<p>How can I configure to use these others mirrors?</p>
</pre>
</details>

</ul>
</details>

<p>There shouldn't be any proxy configured. I didn't find any proxy setting in "Manage Jenkins" => "System".</p>

<p>How can I configure to use these others mirrors?</p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446733&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446733">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<blockquote><p>How can I configure to use these others mirrors?</p></blockquote>

<p>You can't configure to use the other mirrors.  You can download from one of the other mirrors yourself and use the downloaded file.</p>

<p>I assume you did not install this Jenkins controller on a Linux computer using a Linux package manager like "apt", "rpm", "yum", or "dnf".  If you installed with one of those package managers then you should upgrade with the package manager rather than downloading the upgrade from within Jenkins</p>
</pre>
</details>

</ul>
</details>

<blockquote><p>How can I configure to use these others mirrors?</p></blockquote>

<p>You can't configure to use the other mirrors.  You can download from one of the other mirrors yourself and use the downloaded file.</p>

<p>I assume you did not install this Jenkins controller on a Linux computer using a Linux package manager like "apt", "rpm", "yum", or "dnf".  If you installed with one of those package managers then you should upgrade with the package manager rather than downloading the upgrade from within Jenkins</p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446738&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446738">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>If the issue is still visible to you, then it may require that you open a ticket with the <a href="https://github.com/jenkins-infra/helpdesk/issues" class="external-link" target="_blank" rel="nofollow noopener">Jenkins infrastructure help desk</a> for further diagnosis of the issue between your computer and that mirror.  The issue seems to be specific to your installation.  That could be due to the remote site blocking your IP address.  It could be due to something in your local configuration.</p>

<p>Can you download from that URL using <tt>curl</tt> or <tt>wget</tt> as in:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">wget https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>curl -O https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</span>
</pre>
</div></div>

<p>When I run those commands, I see download speeds of about 2.5 MB/s and the downloads succeed.</p>
</pre>
</details>

</ul>
</details>

<p>If the issue is still visible to you, then it may require that you open a ticket with the <a href="https://github.com/jenkins-infra/helpdesk/issues" class="external-link" target="_blank" rel="nofollow noopener">Jenkins infrastructure help desk</a> for further diagnosis of the issue between your computer and that mirror.  The issue seems to be specific to your installation.  That could be due to the remote site blocking your IP address.  It could be due to something in your local configuration.</p>

<p>Can you download from that URL using <tt>curl</tt> or <tt>wget</tt> as in:</p>


<pre>
wget https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war
</span>curl -O https:<span class="code-comment">//ftp-chi.osuosl.org/pub/jenkins/war-stable/2.440.2/jenkins.war</span>
</pre>

<p>When I run those commands, I see download speeds of about 2.5 MB/s and the downloads succeed.</p>

**Comment by lemeurherve** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rafaelsennadasilva.jpg" title="rafaelsennadasilva's avatar" /> rafaelsennadasilva:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73006?focusedId=446752&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446752">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>When I try using wget, the download occurs normally.
Using cURL, the following error occurs:</p>


<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">curl: (60) Peer's certificate issuer has been marked as not trusted by the user. </pre>
</div></div>
<p> </p>

<p>I'm checking with our IT team if there is something blocking the connection.</p>

<p> </p>
</pre>
</details>

</ul>
</details>

<p>When I try using wget, the download occurs normally.<br/>
Using cURL, the following error occurs:</p>



<pre>
curl: (60) Peer's certificate issuer has been marked as not trusted by the user. </pre>
<p> </p>

<p>I'm checking with our IT team if there is something blocking the connection.</p>

<p> </p>
